# Generated by Django 5.0.4 on 2024-05-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0002_profile_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
